# Generated by Django 3.1.3 on 2021-03-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('private', 'PRIVATE'), ('public', 'PUBLIC')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
