# Generated by Django 3.1.3 on 2021-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210307_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=500)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='draft', max_length=10),
        ),
    ]
