# Generated by Django 3.1.3 on 2021-03-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210308_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='ram', upload_to='images', verbose_name='Upload Image'),
        ),
    ]
